on:
  workflow_dispatch:
  push:

jobs:
  upload:
    runs-on: ubuntu-latest
    name: Upload docs directory artifacts
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Upload docs directory
        uses: actions/upload-artifact@v4
        with:
          name: docs
          path: docs
